# Generated by Django 2.0.4 on 2018-05-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('owner', models.CharField(default=None, max_length=255)),
                ('balance', models.CharField(default=None, max_length=255)),
                ('status', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_1', models.CharField(default=None, max_length=255)),
                ('address_city', models.CharField(default=None, max_length=255)),
                ('address_country', models.CharField(default=None, max_length=255)),
                ('address_line1', models.CharField(default=None, max_length=255)),
                ('address_line2', models.CharField(default=None, max_length=255)),
                ('address_line1_check', models.CharField(default=None, max_length=255)),
                ('address_state', models.CharField(default=None, max_length=255)),
                ('address_zip', models.CharField(default=None, max_length=255)),
                ('brand', models.CharField(default=None, max_length=255)),
                ('address_zip_check', models.CharField(default=None, max_length=255)),
                ('country', models.CharField(default=None, max_length=255)),
                ('customer', models.CharField(default=None, max_length=255)),
                ('cvc_check', models.CharField(default=None, max_length=255)),
                ('dynamic_last4', models.CharField(default=None, max_length=255)),
                ('exp_month', models.CharField(default=None, max_length=255)),
                ('exp_year', models.CharField(default=None, max_length=255)),
                ('fingerprint', models.CharField(default=None, max_length=255)),
                ('funding', models.CharField(default=None, max_length=255)),
                ('last4', models.CharField(default=None, max_length=255)),
                ('metadata', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(default=None, max_length=255)),
                ('tokenization_method', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default=None, max_length=255)),
                ('member_1', models.CharField(default=None, max_length=255)),
                ('member_2', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default=None, max_length=255)),
                ('access_level', models.CharField(default=None, max_length=255)),
                ('client_secret', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=None, max_length=255)),
                ('lname', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(default=None, max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('msisdn', models.CharField(default=None, max_length=255)),
                ('stripe_id', models.CharField(default=None, max_length=255)),
                ('card_brand', models.CharField(default=None, max_length=255)),
                ('card_last_four', models.CharField(default=None, max_length=255)),
                ('trial_end_at', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default=None, max_length=255)),
                ('quote', models.CharField(default=None, max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=255)),
                ('tags', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default=None, max_length=255)),
                ('sender', models.CharField(default=None, max_length=255)),
                ('receiver', models.CharField(default=None, max_length=255)),
                ('message', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SocketDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(default=None, max_length=255, unique=True)),
                ('player_id', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(default=0)),
                ('Sender', models.CharField(default=None, max_length=255)),
                ('Receiver', models.CharField(default=None, max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
    ]
