# Generated by Django 2.0.4 on 2018-05-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20180510_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forex',
            old_name='destination',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='forex',
            old_name='source',
            new_name='low',
        ),
    ]
